### ISSUE TITLE
Maps not working on production

### ISSUE THREAD

**Issue by alexgleason** [vegphilly/vegphilly.com#452]
Hi all,

Google Maps is responding with a 403 Forbidden on the live site.

>The Google Maps API server rejected your request. The Google Maps JavaScript API must be downloaded directly from Google's servers. Learn more: https://developers.google.com/maps/documentation/javascript/tutorial#Loading_the_Maps_API

See: http://vegphilly.com/vendors/

**Comment by jfarbowitz** [comment]
@steventlamb Have you seen this? Is this an easy fix?

**Comment by steventlamb** [comment]
@alexgleason Thanks for posting!

I have seen this. It appears to be intermittent - the maps started working when I tried to troubleshoot this seven days ago. I see now that the issue persists.

Strangely, I'm not getting a 403, I'm getting a handful 404s.

It's been a while - we're probably using the API in an outdated fashion and the grace period may have recently ended. I'll try to get our process inline with the current standard.

**Comment by steventlamb** [comment]
this should be fixed in https://github.com/vegphilly/vegphilly.com/pull/453/commits/0d9e1d71219838e3024580729ff77228c701e2e4

disclaimer: I didn't *actually* fix this, I just ripped out the source of the problem. We recently updated our JS stack to use some modern tooling. Looks like something went wrong in the process with how we were connecting to the google maps API. I've reverted the JS to a state that was known to work for a long time. Everything appears back in order, I'll keep an eye on it in the meantime as well.
